# -*- coding: utf-8 -*-
"""Aulas_Estatística

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBeaWB3EJ7CXVaS4BorGdNOSdm5XIzxl

## Variância
"""

#Importando a biblioteca
import statistics
#Lista de números
numeros=[1.59,1.58,1.55,1.67,1.75,1.65,1.55,1.67,1.80,1.72]
#calculando a Variacia
variancia = statistics.variance(numeros)
#Exibindo o resultado
print("A variância dos números é",variancia)

"""## Média"""

#Importando a biblioteca
import statistics
#Lista de números
numeros=[1.59,1.58,1.55,1.67,1.75,1.65,1.55,1.67,1.80,1.72]
#calculando a Média
media = sum(numeros)/ len(numeros)
#Exibindo o resultado
print("A média dos números é ",media)

"""## Moda"""

#Importando a biblioteca
import statistics
#Lista de números
numeros=[1.59,1.58,1.55,1.67,1.75,1.65,1.55,1.67,1.80,1.72]
#calculando a moda
moda = statistics.mode(numeros)
#Exibindo o resultado
print("A moda dos números é",moda)

"""## Mediana"""

#Importando a biblioteca
import statistics
#Lista de números
numeros=[1.59,1.58,1.55,1.67,1.75,1.65,1.55,1.67,1.80,1.72]
#calculando a mediana
mediana = statistics.median(numeros)
#Exibindo o resultado
print("A mediana dos números é",mediana)

"""
## Probabilidade


"""

dados = [1,2,3,4,5,6]
print(sorted({(a,b) for a in dados for b in dados}))

dados = [1,2,3,4,5,6]
resultado = sorted({(a,b) for a in dados for b in dados})
qtde = len(resultado)
num = 0
lista = []
for i in range (qtde):
   if(resultado[i] [0] + resultado [i] [1]) % 5 == 0:
     lista.append(resultado[i])
     num += 1
print("Probabilidade =", round(num / qtde, 2))
print("dados =", lista)

import itertools
urna1 = ["v" , "v" , "b" , "b" , "a"]
urna2 = ["v" , "b" , "b" , "b" , "a" , "a" , "a"]
v = 0
total = 0
for a in urna1:
   for b in urna2:
       total += 1
       if a == "v" or b == "v":
          v += 1
print("Probabilidade de pelo menos 1 bola vermelha = ", v/total)

import random
numero = [0] * 10
for i in range(100):
    n = random.randint(1,10)
    numero [n-1] +=1
for i in range(10):
  print("O número ", i+1, "apareceu" , numero[i], "vezes")

import itertools
urna1 = ["v" , "v" , "v" , "b" , "b" , "b" , "b"]
urna2 = ["v" , "v" , "b" , "b" , "b" , "b" , "b" , "a"]

resultado = []
urna = []
for a in urna1:
    urna = urna2.copy()
    urna.append(a)
    for b in urna :
        resultado.append(b)
total = len(resultado)
print("Probabilidade Vermelho = ",
      round(resultado.count("v")/total,2))
print("Probabilidade Branco = ",
      round(resultado.count("b")/total,2))
print("Probabilidade Azul = ",
      round(resultado.count("a")/total,2))

"""## Análise combinatória"""

# prompt: Exemplos de análise combinatória

# Função para calcular o fatorial de um número
def fatorial(n):
  """Calcula o fatorial de um número."""
  if n == 0:
    return 1
  else:
    fat = 1
    for i in range(1, n + 1):
      fat *= i
    return fat

# Exemplo de permutação simples
def permutacao_simples(n):
  """Calcula o número de permutações simples de n elementos."""
  return fatorial(n)

# Exemplo de combinação simples
def combinacao_simples(n, k):
  """Calcula o número de combinações simples de n elementos tomados k a k."""
  return fatorial(n) // (fatorial(k) * fatorial(n - k))

# Exemplos de uso
n = 5
k = 3

print(f"Permutações simples de {n} elementos: {permutacao_simples(n)}")
print(f"Combinações simples de {n} elementos tomados {k} a {k}: {combinacao_simples(n, k)}")

"""## regressão linear"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Dados de exemplo (variável independente X e dependente Y)
x = np.array([[1], [2], [3], [4], [5]])  # X como matriz (necessário para o scikit-learn)
y = np.array([1, 2, 3, 4, 5])  # valores de y

# Criando o modelo de regressão linear
model = LinearRegression()

# Ajustando o modelo aos dados
model.fit(x, y)

# Exibindo os coeficientes da regressão
print(f"Coeficiente (inclinação): {model.coef_[0]}")
print(f"Intercepto: {model.intercept_}")

# Fazendo uma previsão
x_new = np.array([[6]])  # valor novo para fazer a previsão
y_pred = model.predict(x_new)
print(f"Previsão para x = 6: {y_pred[0]}")

# Visualizando a regressão
plt.scatter(x, y, color='blue')  # gráfico de dispersão dos dados originais
plt.plot(x, model.predict(x), color='red')
plt.title('Regressão Linear Simples')
plt.xlabel('x')
plt.ylabel('y')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Dados de exemplo com variáveis dispersas
np.random.seed(0)  # Definindo semente para reprodutibilidade
x = np.random.rand(100, 1) * 10  # Variável independente (dispersa entre 0 e 10)
y = 2 * x + np.random.randn(100, 1) * 2  # Variável dependente (com ruído)

# Criando o modelo de regressão linear
model = LinearRegression()

# Ajustando o modelo aos dados
model.fit(x, y)

# Exibindo os coeficientes da regressão
print(f"Coeficiente (inclinação): {model.coef_[0][0]}")
print(f"Intercepto: {model.intercept_[0]}")

# Fazendo uma previsão
x_new = np.array([[6]])
y_pred = model.predict(x_new)
print(f"Previsão para x=6: {y_pred[0][0]}")

# Visualizando a regressão
plt.scatter(x, y, color='blue')  # Gráfico de dispersão dos dados originais
plt.plot(x, model.predict(x), color='red')
plt.title('Regressão Linear com Variáveis Dispersas')
plt.xlabel('x')
plt.ylabel('y')
plt.show()

"""## Correlação

"""

# Importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

# Dados de exemplo: Temperatura (°C) e Vendas de Agasalhos (unidades)
dados = {
    'temperatura': [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
    'vendas_agasalho': [500, 450, 400, 350, 300, 250, 200, 150, 100, 50]
}

# Criando um DataFrame
df = pd.DataFrame(dados)

# Calculando a correlação
correlacao = df.corr()

print("Matriz de Correlação:")
print(correlacao)

# Visualizando a relação com um gráfico de dispersão
plt.scatter(df['temperatura'], df['vendas_agasalho'], color='blue')
plt.title('Correlação Negativa: Temperatura vs Vendas de Agasalhos')
plt.xlabel('Temperatura (°C)')
plt.ylabel('Vendas de Agasalhos (unidades)')
plt.show()

# Calculando a correlação de Pearson
correlacao_pearson, p_valor = pearsonr(df['temperatura'], df['vendas_agasalho'])
print(f"Correlação de Pearson: {correlacao_pearson}")
print(f"P-Valor: {p_valor}")

"""## Modelo com Machine Learning

"""

# Importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split  # Corrigido: model_selction para model_selection
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Dados de exemplo: Horas de estudo vs pontuação exame
horas_estudo = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)
pontuacao = np.array([30, 35, 50, 60, 65, 70, 80, 85, 90, 95])

# Dividindo os dados em treino e teste (80% treino, 20% teste)
x_train, x_test, y_train, y_test = train_test_split(horas_estudo, pontuacao, test_size=0.2, random_state=42)  # Corrigido: ranom_state para random_state

# Criando o modelo de regressão linear
modelo = LinearRegression()

# Treinando o modelo
modelo.fit(x_train, y_train)

# Fazendo previsões no conjunto de teste
y_pred = modelo.predict(x_test)

# Avaliando o modelo com erro quadrático médio
mse = mean_squared_error(y_test, y_pred)
print(f"Erro quadrático médio: {mse}")

# Visualizando a linha de regressão
plt.scatter(horas_estudo, pontuacao, color='blue', label='Dados Reais')
plt.plot(horas_estudo, modelo.predict(horas_estudo), color='red', label='Linha de Regressão')
plt.xlabel('Horas de Estudo')
plt.ylabel('Pontuação')
plt.title('Regressão Linear: Horas de Estudo vs Pontuação')
plt.legend()
plt.show()

#prompt : regressão linear simples com 10 variavéis
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

#Generate sample data(replace with your actual data)
x = np.random.rand(100, 10) # 100 simples, 10 feactures
y = 2*x[:, 0] +3*x[:, 1] - x[:, 2] + 0.5*x[:, 3] + np.random.randn(100) # Exemple lienear relationship

#Create a pandas datframe for eaiser handling (optional but recommended)
df = pd.dataframe(x, columns = [f'feacture_{i}' for in range(10)])
df['target'] = y

#Separate features (x) and target (y)
x = df.drop('target', axis = 1)
y = df['target']

#Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

#creat and trin the linear regression model
model = model.predict(x_test)